### ISSUE TITLE
Series.from_list/2 throws argument error when opts != [] in some cases

### ISSUE THREAD

**Issue by kylewhite21** [elixir-explorer/explorer#1000]
In many cases casting to a series and converting the data type in one shot fails, but converting to a series and then casting works. I'm not rusty enough to know why.

```
iex(2)> S.from_list([1, 2], dtype: :string)
** (ArgumentError) argument error
    (explorer 0.9.2) Explorer.PolarsBackend.Native.s_from_list_str("", [1, 2])
    (explorer 0.9.2) lib/explorer/polars_backend/series.ex:24: Explorer.PolarsBackend.Series.from_list/2
    iex:2: (file)
```

```
iex(2)> S.from_list([1, 2]) |> S.cast(:string)
#Explorer.Series<
  Polars[2]
  string ["1", "2"]
>
```

other examples:
```
alias Explorer.Series, as: S

# opts != [] errors
S.from_list(["1", "2"], dtype: {:u, 16})
S.from_list(["1", "2"]) |> S.cast({:u, 16})

# opts != [] errors
S.from_list([1.5, 2.5], dtype: {:u, 16})
S.from_list([1.5, 2.5]) |> S.cast({:u, 16})

# both work
S.from_list([1, 2], dtype: {:f, 32})
S.from_list([1, 2]) |> S.cast({:f, 32})
```

**Comment by josevalim** [comment]
Yes, this is expected. `from_list` mostly does not perform casting except few cases (like ints/floats), you must pass the exact data type. That's because it is very hard and expensive to do the casting at that level. Once you have the data structure in memory and you know exactly what it looks like, it is much easier.

**Comment by kylewhite21** [comment]
Got it, thanks for the fast reply!

**Comment by josevalim** [comment]
Fantatic, and i pushed some docs to avoid future confusion!
