### ISSUE TITLE
Potential improvement for DataFrame Access docs

### ISSUE THREAD

**Issue by mooreryan** [elixir-explorer/explorer#1001]
I was thinking that it could be useful to mention what happens when trying to access a `DataFrame` column that does not exist.

The docs mention that `DataFrame` implements `Access`: 

> [Explorer.DataFrame](https://hexdocs.pm/explorer/Explorer.DataFrame.html) also implements the [Access](https://hexdocs.pm/elixir/Access.html) behaviour (also known as the brackets syntax).

When using the bracket access syntax, an error is raised rather than returning `nil`, as the [`Access` docs](https://hexdocs.pm/elixir/Access.html) mention:

> Both return nil if the key does not exist

Here is what happens:

```elixir
df =
  DataFrame.new(
    a: [1, 2, 3],
    b: [10, 20, 30]
  )

df["c"]

** (ArgumentError) could not find column name "c". The available columns are: ["a", "b"].
If you are attempting to interpolate a value, use ^c.
```

I was thinking an example like this in the `DataFrame` docs could be helpful.  If this would be welcome, I could open a PR request for review.

(For more context, this is related to a [question](https://elixirforum.com/t/access-behaviour-for-explorer-dataframe/66691) I asked on the Elixir Forum.)

**Comment by josevalim** [comment]
Please send a PR adding clarifications to our docs on Access, we can work on it together :)
