### ISSUE TITLE
`Explorer.DataFrame.filter_with` doesn't work with empty list as result of the callback

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-explorer/explorer#1021]
```
** (ArgumentError) expecting the function to return a single or a list of boolean LazySeries, but instead it contains:
[]
    (explorer 0.10.0) lib/explorer/data_frame.ex:2656: Explorer.DataFrame.filter_without_boolean_series_error/1
```

It would be great to have this support an empty list as well (no filtering), but if that's not easily done than at least the typespec for the callback should be adjusted from

```
(Explorer.Backend.QueryFrame.t() -> Explorer.Series.lazy_t() | [Explorer.Series.lazy_t()])
```

to

```
(Explorer.Backend.QueryFrame.t() -> Explorer.Series.lazy_t() | [Explorer.Series.lazy_t(), ...])
```

**Comment by billylanchantin** [comment]
@LostKobrakai Thanks for the report!

I think we should accept an empty list of filters. I see no reason not to and it should be a super easy patch.

But first: are the semantics what I think they are? I'm thinking of situations like this where logic dictates certain outcomes for consistency:

```elixir
Enum.any?([], fn _ -> true end)
#=> false

Enum.all?([], fn _ -> false end)
#=> true
```

Here, I believe this should be true in all cases:

```elixir
df1 = DataFrame.new(...)
df2 = DataFrame.filter_with(df1, [])
assert df1 == df2
```

Is that right?

**Comment by josevalim** [comment]
That's right. A filter expects all conditions to be true and then the row is retained. So it is equivalent to `all?`.

**Comment by LostKobrakai** [comment]
Yeah, that would be my understanding. Not providing a filter means no condition to filter by means nothing is filtered away.

**Comment by billylanchantin** [comment]
@LostKobrakai Should be fixed on `main` now. Not sure when it'll be released but hopefully that unblocks you.

**Comment by LostKobrakai** [comment]
Thanks for the quick turnaround.

I worked around it for now appending a condition, which is always true for all records. So I might wait for the next release.
