### ISSUE TITLE
`Explorer.DataFrame.ungroup(df, :all)` fails

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-explorer/explorer#1035]
`Explorer.DataFrame.ungroup(df, :all)` based on the typespec suggests to ungroup all columns, but I get this error:

`** (ArgumentError) could not find column name "all". The available columns are: …`

Looking at the code I also don't see `:all` handled, but `..`

**Comment by viniciussbs** [comment]
The [documentation](https://hexdocs.pm/explorer/Explorer.DataFrame.html#ungroup/2) of `Explorer.DataFrame.ungroup/2` at version `0.10.1` says:

> Accepts a list of group names. If groups is not specified, then all groups are removed.

And this example is provided to ungroup all:

```elixir
Explorer.DataFrame.ungroup(df)
```

I've tried that, but I also see this error message, so it looks like both ways don't work.

**Comment by philss** [comment]
@LostKobrakai thanks for pointing out. The typespec was incorrect. I removed the `:all` from it.

@viniciussbs can you share the full code sample you tested? I tried what is in the docs and it works fine.

**Comment by viniciussbs** [comment]
@philss It's working. Probably I was getting trouble with something else. Thanks!
