### ISSUE TITLE
Explorer installation fails due aws_signature doesn't exist

### ISSUE THREAD

**Issue by RobinBeekhof** [elixir-explorer/explorer#1039]
Hy, I'm trying to install Explorer in livebook (v0.14.5) running locally on a M1 macbook

```
Mix.install([
  {:explorer, "~> 0.10.1"}
])
```

However, I get this error:

```
Resolving Hex dependencies...
Resolution completed in 0.027s
Because explorer >= 0.7.0 depends on aws_signature which doesn't exist, explorer >= 0.7.0 is forbidden.
So, because your app depends on explorer ~> 0.10.1, version solving failed.
```

**Comment by josevalim** [comment]
It is weird it says `aws_signature` does not exist. Perhaps you have a corrupted index? Can you try removing `~/.hex/cache.ets` and let us know if it works? If it doesn't, try deleting registry.ets and registry.ets.gz next.
