### ISSUE TITLE
Recommendations for preprocessing data before it gets into a clean DataFrame?

### ISSUE THREAD

**Issue by thbar** [elixir-explorer/explorer#1042]
Hello!

I am ingesting a largish amount of independently produced CSV files (with very varying levels of quality).

I typically encounter situations like:
- a CSV field is `[3.812,9.897]` to describe a geo point in a single column (which I need to expand into 2 columns)
- the dtypes system will correctly stop me when a boolean is actually stored as `0` or `1`
- some files are latin1 and not UTF-8 (this one, I guess, will have to be processed externally first)

I love the comfort of the dataframes. Is it a good idea to create a non-typed DataFrame, where columns are "strings" initially, mutate there because it's convenient, and later move the data into a strictly-typed DataFrame, once the data is more or less ready for that?

I could also preprocess the CSV as a stream myself, and pass that to `DataFrame.new`?

Are there other options? 

Thanks!

**Comment by billylanchantin** [comment]
I'm assuming here that you're stuck with CSV and can't generate the data in `.parquet` files or similar which have stricter types.

> Is it a good idea to create a non-typed DataFrame, where columns are "strings" initially, mutate there because it's convenient, and later move the data into a strictly-typed DataFrame, once the data is more or less ready for that?

This is what I'd try first. My guess is that Rust/Polars will be able to process the strings faster than many other Elixir-based preprocessing methods. I've seen Explorer load a 10M line CSV and do a simple transform on it in like 2 seconds.

Depending on what you're doing, other datastores may also be worth considering. I can recommend DuckDB and Clickhouse. They both have good CSV support and are designed for OLAP use cases. Plus there's always good ole Postgres if that's what you're more familiar with.

**Comment by thbar** [comment]
> I'm assuming here that you're stuck with CSV and can't generate the data in `.parquet` files or similar which have stricter types.

The CSV is a "regulatory choice" to ensure that non technical person can produce the data easily, so yes, your assumption is correct!

> This is what I'd try first. My guess is that Rust/Polars will be able to process the strings faster than many other Elixir-based preprocessing methods. I've seen Explorer load a 10M line CSV and do a simple transform on it in like 2 seconds.

Excellent. Those CSV are numerous but overall small (the total volume of all files will be in the 100k-400k range max). Thanks, I will try that first.

> Depending on what you're doing, other datastores may also be worth considering. I can recommend DuckDB and Clickhouse. They both have good CSV support and are designed for OLAP use cases. Plus there's always good ole Postgres if that's what you're more familiar with.

I'm looking at DuckDB for other use cases, and also use Postgres in the app, but in that case Explorer is perfect and acts as a compressed in-memory store that I can rely on without reaching the database.

Thank you!

I will close for now, and will share some examples right here in case it helps others later.
