### ISSUE TITLE
Preferred way to provide feedback?

### ISSUE THREAD

**Issue by thbar** [elixir-explorer/explorer#1043]
Hello again!

As I continue doing a largish Explorer integration (as mostly an Explorer newcomer), I have started stacking notes on parts that have caught me a bit off-guard, and I would like to contribute that back.

Is it better to create one issue for each topic? Or to group everything in a single issue, once I'm done with my current iteration?

(or anything else outside issues? E.g. ElixirForum?)

Thanks!

**Comment by billylanchantin** [comment]
All 3 options seem fine to me! I lean towards an issue per item unless it's a lot (say more than 10). Then I'd do just one issue with bullets.

**Comment by thbar** [comment]
Perfect, thanks. Didn't want to overload things here if it wasn't the right channel. So far I'm at <10 so I'll start with one issue per topic. Thanks!
