### ISSUE TITLE
Incompatible Nx version with Axon

### ISSUE THREAD

**Issue by mvkvc** [elixir-explorer/explorer#220]
Hello,

I wanted to use the explorer library with the other new elixir-nx packages, however Mix is saying that the version of Nx is not compatible with EXLA or Axon. Am I making a mistake or is the current state that these cannot be used together in a project?

![image](https://user-images.githubusercontent.com/40243568/167039611-937b3fae-2883-41a2-8ffb-b3307443a01e.png)

Thank you!

**Comment by jonatanklosko** [comment]
Hey @mvkvc! Next version of Explorer will have `nx` as an optional dependency, so this should no longer be an issue. Meanwhile, you should be able to resolve this conflict by adding `{:nx, "~> 0.2.0", override: true}` to your dependencies :)
