### ISSUE TITLE
Allow stable sorting to be turned off

### ISSUE THREAD

**Issue by josevalim** [elixir-explorer/explorer#554]
Also verify if we should expose the multithreaded option during sorting or not.

**Comment by kimjoaoun** [comment]
Are there downsides in exposing the multithreaded option?

**Comment by philss** [comment]
> Are there downsides in exposing the multithreaded option?

@kimjoaoun I don't think so. I think we can have both options. If you want to take this one, please go ahead!

**Comment by kimjoaoun** [comment]
> > Are there downsides in exposing the multithreaded option?
> 
> @kimjoaoun I don't think so. I think we can have both options. If you want to take this one, please go ahead!

Nice, I'll take it.

**Comment by billylanchantin** [comment]
Closed by: https://github.com/elixir-explorer/explorer/pull/771

@kimjoaoun Sorry! I didn't see that you'd called dibs on this.

**Comment by billylanchantin** [comment]
@josevalim Oh I may have jumped the gun on this one. Can you confirm that https://github.com/elixir-explorer/explorer/pull/771 closed this?

**Comment by josevalim** [comment]
It is all good!

**Comment by kimjoaoun** [comment]
> Closed by: #771
> 
> @kimjoaoun Sorry! I didn't see that you'd called dibs on this.

No problem at all!
