### ISSUE TITLE
Allow diff of date and datetime series

### ISSUE THREAD

**Issue by sasikumar87** [elixir-explorer/explorer#568]
How should the API be like?

**Comment by josevalim** [comment]
Can you expand what you mean?

**Comment by sasikumar87** [comment]
Assuming a dataframe like `DataFrame.new(a: [~D[2023-04-11], ~D[2023-04-10]], b: [~D[2023-04-06], ~D[2023-04-05]])`, I need to find the diff between `a` and `b`.

**Comment by josevalim** [comment]
I see! How is it called in Pandas and Polars? What about dplyr? Those can provide some initial reference points.

**Comment by sasikumar87** [comment]
Pandas seems to support `-` for date and datetime. For conversion to different units like day, hour etc, they allow this subtracted value to be divided by [timedelta64](https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-and-timedelta-arithmetic) type, which can specify the unit of measurement.

Polars also seems to support `-` through [sub](https://docs.rs/polars/latest/polars/export/chrono/struct.Date.html#method.sub), returning Duration type. From duration, we can calculate different units of measurement with functions like `num_days`, `num_hours` etc.

dplyr seems to have [difftime](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/difftime) which can support both date and datetime with `units` option to return as weeks, days, hours, etc.

In Elixir, `Date.diff/2` returns number of days, while `NaiveDateTime.diff/3` returns number of seconds / milliseconds etc based on third argument, which cannot be greater than a second.

Given this, I'm thinking of `Series.diff/3`, with third argument as an atom that supports `weeks`, `days`, `hours`, `minutes`, `seconds`, `milliseconds`, `microseconds`, `nanoseconds`, all the values that can be converted from polars Duration type. And we can also make third argument optional with `days` as default if the the series is of date type and `seconds` for datetime type, to maintain Elixir's default convention.

Will this be ok?

**Comment by sasikumar87** [comment]
One problem is `diff` sounds like an arithmetic operation which supports numbers, but here we are using it only for date and datetime. Can it be `Series.diff_date/3` and `Series.diff_datetime/3` ?

**Comment by josevalim** [comment]
Yes, although we need to decide if it is `date_diff` or `diff_date` (I think I prefer the first). The other question is about how different types interplay with other. The difference between two dates has a granularity of days. The difference of a time unit would have the granularity of seconds. So perhaps it should be `date_diff` (days precision by default, perhaps ignoring any time component) and `time_diff` (seconds precision by default, always considering time components). For starter, we could support only equal types:

    date_diff(:date, :date)
    time_diff(:time, :time)
    time_diff(:datetime, :datetime)

WDYT?

**Comment by sasikumar87** [comment]
Agree

**Comment by sasikumar87** [comment]
@Hanspagh I haven't started on this. Please feel free to pick it up :)

**Comment by Hanspagh** [comment]
After playing around and working on this yesterday, I started to wonder if we need to make a distinction between `date_diff` and `time_diff`. Essentially we are trying to make it easier to get a diff between two times in some format. If I with the current suggestion wanted the hour diff between two dates, I would still have to manually convert days output to hours. My suggestion would be to just have one `diff`(name to be decided) which can take any date, datetime or time and return a diff in a requested format, days, minutes, seconds, microseconds. This would make the interface easy and I dont have to think about which time/date diff to use.  

The other direction to go in would be to support a duration dtype like the pandas `Timedelta`

WDYT?

**Comment by josevalim** [comment]
I was thinking the same but i thought we could call it `duration(s1, s2)`, which computes the duration between two timestamps. Polars ships with a Duration dtype and perhaps we should support it. It is just annoying that it has a TimeUnit, which makes its usage more annoying. We can go in this direction but hold on a day or two. I am currently migrating everything to be nanoseconds by default.

**Comment by Hanspagh** [comment]
Either `duration` or just support subtraction with two datetime, maybe it is cleaner with an explicit method.

**Comment by Hanspagh** [comment]
Hi @josevalim. How is it looking with the conversion to nanoseconds?

**Comment by Hanspagh** [comment]
No problem, I start looking into this again.

**Comment by anthony-khong** [comment]
Hi all, I quite like to have this feature too. May I pick it up and try to take a stab at it?

Are we going for `duration(s1, s2, time_unit)`? Or the original `date_diff/2` and `time_diff/3`?

**Comment by Hanspagh** [comment]
Sure, I didn't have time work further to this. I think we should go with the duration, since it will make the interface a bit simpler and we can utilize the underlying Duration struct

**Comment by anthony-khong** [comment]
Putting this here for discoverability: José's relevant [remark and suggestion on how to move forward](https://github.com/elixir-explorer/explorer/pull/642#issuecomment-1623283607) in #642

**Comment by Hanspagh** [comment]
I think this was closed by #696
