### ISSUE TITLE
`mix ci` difficulties on MacOS as an Elixir beginner

### ISSUE THREAD

**Issue by cnpryer** [elixir-explorer/explorer#657]
Hi! I'm eager to dig in here. I've been wanting to learn Elixir for a while, so I'm hoping to get my feet wet here.

For context I've used `DataFrame`s (Python) for a while now, so I've been curious of this project for a bit.

**Platform**: MacOS 13.4.1

To get set up I needed to:
1. `rustup override set <README nightly>`
2. `mix deps.get`
3. `mix ci`

A few questions and I apologize, I'm very new to Elixir:

- Would it make sense to put *this all* behind `mix ci` or some equivalent command?
- If not, would this be a good README contrib? Maybe I'm just not familiar enough yet to realize it's current state is super standard.
- Would at least automatic Rust toolchain targeting be possible? That would be a nice QoL improvement, I think. 

Really cool project!

**Comment by josevalim** [comment]
I think those are distinct things. `deps.get` and `rustup` are part of "setup", you only run it once, and `ci` is a later step. In any case, I am not sure if we should assume users are using `rustup`.

**Comment by cnpryer** [comment]
Makes sense. Thanks for the quick response!
