### ISSUE TITLE
Add binding to str.slice and/or str.split and/or add trim/2

### ISSUE THREAD

**Issue by DeemoONeill** [elixir-explorer/explorer#663]
Currently doing data sanitizing (specifically strings) with explorer can be frustrating,

Currently the only string ops exposed are
    [contains/2](https://hexdocs.pm/explorer/Explorer.Series.html#contains/2)
    [downcase/1](https://hexdocs.pm/explorer/Explorer.Series.html#downcase/1)
    [trim/1](https://hexdocs.pm/explorer/Explorer.Series.html#trim/1)
    [trim_leading/1](https://hexdocs.pm/explorer/Explorer.Series.html#trim_leading/1)
    [trim_trailing/1](https://hexdocs.pm/explorer/Explorer.Series.html#trim_trailing/1)
    [upcase/1](https://hexdocs.pm/explorer/Explorer.Series.html#upcase/1)

It would be good if we could get slice or split into explorer, so things like trimming the currency symbol from financial data can be done in explorer rather than iterating over the data in elixir.

Another nice to have could be trim/2 which takes in which characters to trim (similar to the py-polars str.strip). Currently there is trim/1 which just does white space. 

I don't which ones go best with "constraining your options" philosophy, whilst still giving tools to do more effecient string manipulation.

If I could be tagged in any PR that comes from this, that would be great, i'd love to see how the bindings are added so I can help contribute in future.

**Comment by josevalim** [comment]
Hi @DeemoONeill! Thanks for opening the issue. We could at least add trim/2, trim_leading/2 and trim_trailing/2 where the second argument is the string to trim. PRs from the overall community are very welcome!

Here is a template one can follow to add said functions: https://github.com/elixir-explorer/explorer/pull/627 :)

**Comment by josevalim** [comment]
`slice/3` would also be very convenient, agreed! :+1:

**Comment by DeemoONeill** [comment]
While working on trim, i think i've found a bug in the original implementation. the doctest is 

```elixir
      iex> s = Explorer.Series.from_list(["  abc", "def  ", "  bcd"])
      iex> Explorer.Series.trim(s)
      #Explorer.Series<
        Polars[3]
        string ["abc", "def", "bcd"]
      >
 ```
 
 and this passes.

Changing this to 
```elixir
      iex> s = Explorer.Series.from_list(["  abc", "def  ", "  bcd   "])
      iex> Explorer.Series.trim(s)
      #Explorer.Series<
        Polars[3]
        string ["abc", "def", "bcd"]
      >
```

causes it to fail. 

the docs for the rust

`s1.utf8()?.replace()` say "Replace the leftmost regex-matched (sub)string with another string"

i think s_trim needs to do two passes to ensure that characters are removed from both the front and back

**Comment by josevalim** [comment]
Good find, feel free to include a fix (and updated tests) for it too!

**Comment by DeemoONeill** [comment]
https://github.com/elixir-explorer/explorer/pull/664

PR is here, I've not done trim_leading/2 or trim_trailing/2 yet, I want to make sure i've done this properly first. happy to add as part of this PR or to do another one

**Comment by josevalim** [comment]
Awesome job @DeemoONeill! <3
