### ISSUE TITLE
[Question] Linting Elixir code as an Elixir beginner

### ISSUE THREAD

**Issue by cnpryer** [elixir-explorer/explorer#673]
Q: **Is there any interest in more advanced code analysis for this repository?** 

I tried asking this in the Elixir Discord, but I wasn't really satisfied with the answer. I've also done some research. IIUC `mix compile --warnings-as-errors` will act as a kind of analyzer, emitting errors for potential code corrections.

From reading about code analysis for Elixir, it looks like projects such as `credo` and `dialyzer` (from the Erlang ecosystem?) are used for more advanced code analysis. I also noticed the Elixir repo itself uses `dialyzer` for code analysis.

I'm using this issue to gauge this project's stance on development tooling and to understand what the recommendation currently is.

**Comment by josevalim** [comment]
Hi @cnpryer, I think the ElixirForum will be a better place for such discussions. I am personally not a big fan of Dialyzer because its error messages often leave to be desired but I have seen both adopted with great success, especially on _applications_. :)
