### ISSUE TITLE
Pairwise operations

### ISSUE THREAD

**Issue by cristineguadelupe** [elixir-explorer/explorer#680]
The idea is to provide an abstraction that allows series operations that operate between two series to be applied pairwise across an entire data frame, ignoring the columns that have unsupported types for the given operation.

`DF.pairwise(df, :correlation)` should be similar to https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html

## UPDATE

We decided to go with the same naming from the `Series` for the operations in the `DataFrame`.
So we now have a function called `correlation/2`. The idea is to add more pairwise operations.

- [x] `correlation/2` - https://github.com/elixir-explorer/explorer/pull/759
- [x] `covariance/2` -  https://github.com/elixir-explorer/explorer/pull/763

**Comment by josevalim** [comment]
For completeness, how does that work in dplyr? Perhaps they would use across? That’s something easy to do with our query today.

**Comment by jcmkk3** [comment]
> For completeness, how does that work in dplyr? Perhaps they would use across? That’s something easy to do with our query today.

In the tidyverse ecosystem, I think that the idiomatic way would be to use the [widyr](https://github.com/juliasilge/widyr) package.
