### ISSUE TITLE
mutate only certain rows based on a filter?

### ISSUE THREAD

**Issue by kylewhite21** [elixir-explorer/explorer#689]
Is it possible to efficiently mutate a DataFrame based on the results of a filter? In Pandas, it'd look something like 
```
df.loc[df["type"] == 1, "result"] = "Type 1"
```
I can think of several ways to work around this (inefficiently casting to a List and back is one) but wanted to check if there was a better way.

**Comment by philss** [comment]
Today you can use [`Explorer.Series.select/3`](https://hexdocs.pm/explorer/Explorer.Series.html#select/3) for that:

```elixir
require Explorer.DataFrame, as: DF

df = DF.new(%{names: ["Alice", "Bob", "John"], grade: [10, 4, 6]})
DF.mutate(df, %{"result" => select(grade > 5, from_list(["passed"]), from_list(["failed"]))})
```

Resulting in:

```
#Explorer.DataFrame<
  Polars[3 x 3]
  grade integer [10, 4, 6]
  names string ["Alice", "Bob", "John"]
  result string ["passed", "failed", "passed"]
>
```

@kylewhite21 does this works for you?

PS: in theory we could avoid the usage of `from_list/1` and use the string directly, but there is a tiny bug today. I'm going to fix it soon.

**Comment by kylewhite21** [comment]
@philss thanks for the quick reply!

That works for some use cases, but say you wanted another mutate that will assign a `result` of `exceptional` to every row where `grade >= 10`? That'd overwrite `result`s for `grade < 10`. (Or maybe there is another `Series` option that could handle a `case`?)

**Comment by josevalim** [comment]
You can nest the selects. There is an open issue to make this easier to write. :)

**Comment by philss** [comment]
@kylewhite21 you would have to nest some `select/3`:

```elixir
require Explorer.DataFrame, as: DF

df = DF.new(%{names: ["Alice", "Bob", "John", "Maria"], grade: [10, 4, 6, 15]})

DF.mutate(df,
  result:
    select(
      grade > 5,
      select(grade > 10, from_list(["exceptional"]), from_list(["passed"])),
      from_list(["failed"])
    )
)
```

Like @josevalim mentioned, there is this issue open to improve this: https://github.com/elixir-explorer/explorer/issues/515

**Comment by kylewhite21** [comment]
Actually never mind, I realized you can just pass the existing results straight through in the failure case:
```
df = DF.mutate(df, %{"result" => select(grade > 9, from_list(["exceptional"]), result)})
```

I'm good, thanks!
