### ISSUE TITLE
It is not clear how to filter on categories

### ISSUE THREAD

**Issue by brendon9x** [elixir-explorer/explorer#690]
I have searched the forums, Slack and codebase first, but haven't been able to work out if this is expected or not. I am trying to filter based on a category value. Example below:

```elixir
fruit =
  Series.from_list(for i <- 1..10, i > 0, do: :rand.uniform(3) - 1)
  |> Series.categorise(["Apple", "Banana", "Pear"])

fruit |> Series.in(["Apple"])

fruit |> Series.equal("Apple")

fruit |> Series.equal(0)
```

Where this is really important, is when you need to build a UX on top of the Series or DataFrame and offering filtering functionality. You want to populate a dropdown with the set of category members and then filter (or group) on them.

**Comment by josevalim** [comment]
We need a wrapper around: https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.filter.html - this won’t be allowed in queries, so it must raise for lazy backends.

**Comment by cigrainger** [comment]
@josevalim That's what `Series.mask/2` is, no?

```
#[rustler::nif(schedule = "DirtyCpu")]
pub fn s_mask(series: ExSeries, filter: ExSeries) -> Result<ExSeries, ExplorerError> {
    if let Ok(ca) = filter.bool() {
        let series = series.filter(ca)?;
        Ok(ExSeries::new(series))
    } else {
        Err(ExplorerError::Other("Expected a boolean mask".into()))
    }
}
```

**Comment by cigrainger** [comment]
So I think the issue isn't defining the predicate, it's the type mismatch -- how do we provide a categorical scalar value for the comparison in something like `Series.mask(fruit, Series.equal(fruit, "Apple"))`.

**Comment by josevalim** [comment]
@cigrainger ah, perfect, I forgot about `mask`. You are right. We are not comparing :category with none of integer or string and we should. I will address that quickly. :)
