### ISSUE TITLE
Aggregate a series to list in groupby

### ISSUE THREAD

**Issue by lambdaofgod** [elixir-explorer/explorer#697]
I oftentimes encounter a situation where I do something like this in pandas

```
df = pd.DataFrame({"x": ["a", "a"], "y": ["foo1", "foo2"])
xs_with_ys_df = df.groupby("x").apply(lambda gp: list(gp["y"]))
```

I don't see how to apply `mutate` on an Explorer dataframe to get this behavior as the aggregation functions only look like they support scalar operations.

Is it possible to do this in Explorer? How?

**Comment by josevalim** [comment]
Closing this as a dup for now.
