### ISSUE TITLE
&Explorer.DataFrame.print/2 does not print header names if no options is provided

### ISSUE THREAD

**Issue by darkblueorange** [elixir-explorer/explorer#699]
https://github.com/elixir-explorer/explorer/blob/6ee60debd687104f5327e7bc12288ae54da3c05c/lib/explorer/data_frame.ex#L5311C5-L5311C5

Because of the case do df is only filled if option :limit is provided, and then header display is based on the same df (see df.names)

```elixir
    df =
      case opts[:limit] do
        :infinity -> df
        nrow when is_integer(nrow) and nrow >= 0 -> slice(df, 0, nrow)
        _ -> slice(df, 0, @default_sample_nrows)
      end

    types = Enum.map(df.names, &"\n<#{Atom.to_string(df.dtypes[&1])}>")
```

**Comment by josevalim** [comment]
Can you please provide a PR?

**Comment by josevalim** [comment]
Or if you can provide an input and your desired output, we can take a look at it later.

**Comment by darkblueorange** [comment]
My mistake, very sorry. 

First I didn't see correctly DF.print/2 display correctly (scroll bar was exactly positioned so I didn't see the column names).
Second I didn't read correctly the source code, especially I didn't see the "_" collector line (although I was surprised not to see one, I should've triple checked). 

Shame. So sorry to waste your time. Thank you very much for all. I close the issue.

**Comment by josevalim** [comment]
No worries, I had to review the code and I noticed we don't support lazy data frames in there, so I fixed that. :)
