### ISSUE TITLE
Drop_nil for Series missing

### ISSUE THREAD

**Issue by sehHeiden** [elixir-explorer/explorer#715]
While the funtion drop_nil/2 exists for DataFrames, it is missing for Series. 
Could you be so kind to ad it?

**Comment by josevalim** [comment]
PRs welcome. Note this function is not supported by lazy data frames.

**Comment by kimjoaoun** [comment]
Can I take this one, @josevalim?
Ill be opening a PR that closes #554 in a few days, after that I can work on this one.

**Comment by josevalim** [comment]
Yes, definitely!

**Comment by cigrainger** [comment]
Do we need this? Can't you just filter with `Series.mask/2`? e.g. `Series.mask(s, Series.is_not_nil(s))`? One of the biggest complaints I hear about pandas is that there are so many ways to do the same thing. I know that `dplyr` has specifically avoided many redundant convenience functions like this to stay parsimonious. Is there a performance benefit?

**Comment by cigrainger** [comment]
I'll add: one of the reasons I included `DataFrame.drop_nil/2` originally is because it's not trivial to do for a dataframe with `DataFrame.filter/2` (or wasn't before we had `across`). This is trivial to do for a series.

**Comment by sehHeiden** [comment]
I am not, to add the function might add to verbosity, which I consider a good thing.
But in cause, its not added, I think it's a good think to add the alternative to the documentation, so that it can be found by search.

So that someone coming from pandas as I am, has a smoother transition period.

17.10.2023 11:28:39 Christopher Grainger ***@***.***>:

**Comment by josevalim** [comment]
Closing as you can do `Series.filter(s, _ != nil)` in main.
