### ISSUE TITLE
Series.variance/1 population vs sample version

### ISSUE THREAD

**Issue by joustava** [elixir-explorer/explorer#738]
I'm using this library for some studies and came across the population vs sample data variance and according to that, when a series is known to be sample of a population, some sort of bias is accounted for by using n-1 for the denominator.

The [docs](https://hexdocs.pm/explorer/Explorer.Series.html#variance/1) mentions "Gets the variance of the series." and it seems to do that just fine and the Series is assumed to be a sample not a population?

**population version**

$$
\sigma^2 = \frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2
$$

**sample version**

$$
s^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2
$$

Should there be a flag (bias?) accounting for this similar to Series.skew?

**Comment by cigrainger** [comment]
Hey! Thanks for this. You're right it's the sample variance. I think we'll take the approach Pandas takes here and expose delta degrees of freedom and default to 1. You could set it to 0 to calculate the population variance.
