### ISSUE TITLE
Expose ddof option for `Series.covariance/1`

### ISSUE THREAD

**Issue by philss** [elixir-explorer/explorer#743]
This is similar to #740 and it's possible after #742 get merged.

**Comment by billylanchantin** [comment]
Oh nice! I think this may also unlock #729. I tried it a few weeks ago but got stuck on the IPC tests. They treated integer strings a bit loosely, which it looks like this change addresses.

**Comment by philss** [comment]
This one was completed. Thanks, @cigrainger!
