### ISSUE TITLE
An official place to discuss between early-adopters/users?

### ISSUE THREAD

**Issue by thbar** [elixir-explorer/explorer#753]
Hello,

Related:
- https://github.com/elixir-explorer/explorer/issues/723

I'm dabbling more and more with Explorer, often converting small bits of non-Explorer code to Explorer once it's relevant or useful or I want to move into LiveBook and show more stuff.

I often have small questions popping up, that are not necessarily obvious to figure out after reading the documentation (although over time it will get easier).

I am pretty sure there are other early-adopters that would be happy to bounce small questions.

My question is: how can we make sure those exchanges are captured & not lost etc?

I am not sure what the right answer is - could be:
- a Slack channel on the ElixirLang slack
- a tag on the ElixirForum
- GitHub discussions on this repository

In the past I had good success with a StackOverflow tag (as a maintainer it made it easy to point people to a specific response, or let them handle things directly), see https://stackoverflow.com/questions/tagged/kiba-etl.

I am pretty sure Explorer is going to see more and more interesting use-cases, and I want to make sure the knowledge is spread as much as possible!

Thoughts? Thank you!

**Comment by josevalim** [comment]
ElixirForum is the place to go: https://elixirforum.com/c/elixir-framework-forums/nx-forum/105

There is also the #machine-learning channel on the Erlang Ecosystem Foundation Slack. You can request your an invite by creating a free account :)

**Comment by thbar** [comment]
@josevalim thank you!

Would you welcome a PR adding this information at the top of the readme maybe?

**Comment by josevalim** [comment]
@thbar sounds good to me!
