### ISSUE TITLE
Some primitive polars data types are missing

### ISSUE THREAD

**Issue by nsweeting** [elixir-explorer/explorer#764]
Is there any reason why explorer couldn't opt in to some of the more primitive polars data types (i8, i16, u8, u16)?

I'm trying to read a parquet file containing an Int16 and its currently resulting in an error:

```
** (RuntimeError) from_parquet failed: "Polars Error: cannot create series from Int16"
    (explorer 0.7.2) lib/explorer/data_frame.ex:760: Explorer.DataFrame.from_parquet!/2
    #cell:wgfhzb4hdlbpk4mcw4zv7fjhm5ynrkjk:1: (file)
```

It looks like these could be brought in via opt-in data types: https://docs.rs/polars/latest/polars/#compile-times-and-opt-in-data-types

Thanks!

**Comment by josevalim** [comment]
It is currently WIP. We have already added f32 and f64. Integer types are coming next.
