### ISSUE TITLE
Revist the names of `DataFrame.arrange/2` and `DataFrame.arrange_with/2`

### ISSUE THREAD

**Issue by billylanchantin** [elixir-explorer/explorer#766]
There's been some discussion of renaming the `arrange` functions to `sort`. E.g. here:

* https://github.com/elixir-explorer/explorer/pull/762#issuecomment-1846552261

This would align better with the `Series` function names. Plus, the `arrange` names come from R where they were chosen to avoid namespace conflicts. We don't have to worry about that here.

However, this would be a breaking change. This issue is to hash out that discussion.

**Comment by josevalim** [comment]
I am happy to roll with `sort_by` and `sort_with`. We should keep `arrange` and `arrange_with` around with `@deprecated "foobar"` annotations. They can simply delegate to the new `sort_by` and `sort_with`.

**Comment by cigrainger** [comment]
Yep agreed!
