### ISSUE TITLE
Add support for ewm_std and ewm_var

### ISSUE THREAD

**Issue by rtvu** [elixir-explorer/explorer#776]
[#541](https://github.com/elixir-explorer/explorer/issues/541) added support for Series.ewm_mean.

Polars also has functions for ewm_std and ewm_var in [emw.rs](https://github.com/pola-rs/polars/blob/65bf678cecc82d3ad37b6773f2ce4e6f59852b25/crates/polars-ops/src/series/ops/ewm.rs).

Can these functions be added?

**Comment by josevalim** [comment]
Please send PRs. You can look at other recent PRs for examples of adding new functions.
