### ISSUE TITLE
Question/Possible improvement about the encoding option in the DataFrame.from_csv/2 function

### ISSUE THREAD

**Issue by Jhonatannunessilva** [elixir-explorer/explorer#791]
- The documentation for the function [DataFrame.from_csv/2](https://hexdocs.pm/explorer/Explorer.DataFrame.html#from_csv/2-options) is missing an explanation of the "encoding" option.
- And even if this encoding option is passed, the code will only accept the "utf8-lossy" option, as any other string will be considered as "utf8": [io.rs](https://github.com/elixir-explorer/explorer/blob/5c51c26fc70f9a4ac3a6eeefd3c8c1241e5ceeec/native/explorer/src/dataframe/io.rs#L44-L47).
- WDYT? Is it worth including this information in the DataFrame.from_csv/2 docs?

**Comment by philss** [comment]
@Jhonatannunessilva unfortunately we can only accept the [options provided by Polars](https://github.com/pola-rs/polars/blob/b44adb9a27607c19689bffcf237e49327c9087cb/crates/polars-io/src/csv/read.rs#L10). But you are right, we are missing docs around that! Please go ahead if you plan to open a PR for this! :D
