### ISSUE TITLE
Support `Series.map/2` with lists

### ISSUE THREAD

**Issue by cigrainger** [elixir-explorer/explorer#835]
It's intuitive to me to be able to do things like:
```elixir
require Explorer.Series, as: S
s = S.from_list([1, 2], [3, 4], [1, 5, 7]]
S.map(s, max(_))
```

and get
```elixir
#Explorer.Series<
  Polars[3]
  s64 [2, 4, 7]
>
```

**Comment by josevalim** [comment]
This may be tricky because it makes `max` ambiguous: it is both an aggregator and an element-wise operator. We may be able to implement it, but we need to handle the differences properly inside LazySeries.

**Comment by cigrainger** [comment]
Another option would be to just be able to give `Series.max/1` and similar functions a list series directly. In that case:

```elixir
iex> s = S.from_list([1, 2], [3, 4], [1, 5, 7]]
iex> S.max(s)
#Explorer.Series<
  Polars[3]
  s64 [2, 4, 7]
>
```

It would mean that we'd need to support the inner dtype for that series function. I know this can be tricky because it's a recursive dtype.

**Comment by josevalim** [comment]
Yes, that's the same feature, because we need to keep everything consistent since `max` inside DF or Series both need to follow the same backend callbacks. :)

**Comment by billylanchantin** [comment]
Not that we're looking for solutions to this particular problem, but here's a workaround in the meantime:

```elixir
require Explorer.DataFrame, as: DF
require Explorer.Series, as: S

s = S.from_list([[1, 2], [3, 4], [1, 5, 7]])

DF.new(series: s)
# This part will be easier once we have `with_row_index` (or similar)
|> DF.put(:index, S.from_list([0, 1, 2], dtype: :u8))
|> DF.explode(:series)
|> DF.group_by(:index)
|> DF.summarise(agg: max(series))
|> DF.pull(:agg)
# #Explorer.Series<
#   Polars[3]
#   s64 [2, 4, 7]
# >
```

This strategy should work pretty generally.

**Comment by cigrainger** [comment]
Well that would be a pretty practical thing for `row_number()` as discussed in #833.

```elixir
require Explorer.DataFrame, as: DF
require Explorer.Series, as: S

s = S.from_list([[1, 2], [3, 4], [1, 5, 7]])

DF.new(series: s)
# This part will be easier once we have `with_row_index` (or similar)
|> DF.mutate(index: row_number())
|> DF.explode(:series)
|> DF.group_by(:index)
|> DF.summarise(agg: max(series))
|> DF.pull(:agg)
# #Explorer.Series<
#   Polars[3]
#   s64 [2, 4, 7]
# >
```

**Comment by josevalim** [comment]
Given #864, we should probably start considering adding some sort of prefix for list functions that match a series function of the same name.

**Comment by josevalim** [comment]
Closing this as there is already Series.map with other semantics.
