### ISSUE TITLE
Creating Lists / Records in `mutate`

### ISSUE THREAD

**Issue by maennchen** [elixir-explorer/explorer#852]
It would be great if `Explorer.DataFrame.mutate/2` would allow to create lists and structs on the fly.

I'm currently working on a use case where I have to convert a very large dataset (~ 220M rows) from a flat format into a structured format while also doing some other filtering & aggregations.

Example using pseudo code:

```elixir
# Actualy read from `ndjson`, just an example for the contents
[
  %{"phone" => "phonenr", "mobile" => "mobilenr"},
  %{"phone" => "phonenr", "mobile" => nil},
  #...
]
|> DataFrame.new()
|> DataFrame.mutate(
  phone_numbers: drop_nil([
    select(is_nil(phone), nil, %{"type" => "phone", "nr" => phone}),
    select(is_nil(mobile), nil, %{"type" => "mobile", "nr" => mobile})
  ])
)
|> DataFrame.discard([:phone, :mobile])
|> dbg
# => #Explorer.DataFrame<
#   Polars[2 x 1]
#   phones list[struct[2]] [
#     [
#       %{"nr" => "phonenr", "type" => "phone"},
#       %{"nr" => "mobilenr", "type" => "mobile"}
#     ],
#     [%{"nr" => "phonenr", "type" => "phone"}]
#   ]
# >
```

Polars seems to offer [`pl.struct()`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.struct.html), [`pl.all()`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.all.html) and [`exclude()`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.exclude.html), which should make this use case possible.

(This pseudo code also assumes that `Series.drop_nil/1` exists, that is however currently not the case.)

**Comment by josevalim** [comment]
I believe it is a good idea. LazySeries could find maps and convert them into literals recursively.

drop_nil in a mutate is no-no though I think. You can run a filter later on though.

**Comment by billylanchantin** [comment]
> drop_nil in a mutate is no-no though I think. You can run a filter later on though.

@josevalim I had the same reaction, but I think they were using drop_nil on the inner list. So, the resultant series is the same length but each list-element is of a different length.

**Comment by maennchen** [comment]
Exactly. Polars has [`polars.DataFrame.drop_nulls`](https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.drop_nulls.html) as well as [`polars.Expo.drop_nulls`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.Expr.drop_nulls.html)

It should be trivial to implement on `Explorer.Series`.

**Comment by cigrainger** [comment]
Yep, fully in support of this and `drop_nil` on the inner list should be absolutely fine.

**Comment by josevalim** [comment]
@maennchen we support map literals in main. I will create a new issue to add `drop_nil` to lists.
