### ISSUE TITLE
Should we always raise when a column is missing?

### ISSUE THREAD

**Issue by cigrainger** [elixir-explorer/explorer#870]
Feedback from a colleague: he's been tripping over `DataFrame.discard/2` and forced into patterns like `if field in DataFrame.names(df), do: DataFrame.discard(df, field), else: df`. That one feels like it should be a no-op for non-existing fields. I can see the counterargument though, so putting it out there before raising a PR.

**Comment by josevalim** [comment]
I agree for discard we do not need to raise if the field does not exist. :+1:

**Comment by billylanchantin** [comment]
Out of curiosity, how are they using dataframes? For my personal use, I always know which columns are present.

**Comment by cigrainger** [comment]
It's for exporting the search results from a project in Amplified and there are some conditional joins that can lead to variations in the columns that are present.
