### ISSUE TITLE
`{:datetime, :second}` dtype support

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-explorer/explorer#885]
Looking at the initial PR for the precision on datetimes I didn't find seconds as a unit being discussed. I'm dealing with a lit of unix timestamps and doing `{:datetime, :millisecond}` feels wrong given I initially don't have that much precision. Are there any reasons not to support second precision?

**Comment by josevalim** [comment]
If it is supported in polars, I believe we can totally support it here too.

**Comment by LostKobrakai** [comment]
Ah, that's where the limitation is. It only supports the 3 precisions we have it seems. I was looking at the arrow docs, which were linked on #867 and it showed second as a unit.
