### ISSUE TITLE
Add :streaming option to DataFrame.to_csv/3

### ISSUE THREAD

**Issue by ryancurtin** [elixir-explorer/explorer#888]
I have a use case where I would like to stream a large lazy `DataFrame` to a CSV without having to load the entire dataset in memory, and I was looking to implement a streaming option to the `to_csv/3` function, similar to `DataFrame.to_parquet/3`.  

I've already been able to make this work in a fork using the Polars [sink_csv](https://docs.rs/polars/latest/polars/prelude/struct.LazyFrame.html#method.sink_csv) function under the hood.  Please let me know what you think and I will submit my PR.  Thanks!

**Comment by josevalim** [comment]
Yes, a pull request would be welcome to any of our API‘s that do not support streaming yet
