### ISSUE TITLE
Filter throwing undefined variable error

### ISSUE THREAD

**Issue by olmohake** [elixir-explorer/explorer#905]
In Livebook

```elixir
Mix.install([
  {:explorer, "~> 0.8.2"}
])
df = Explorer.DataFrame.new(col1: ["a", "b", "c"], col2: [1, 2, 3])
Explorer.DataFrame.filter(df, col2 > 2)
```

=> error: undefined variable "col2"
  #cell:3fcusi3khmd5jay3:5

**Comment by josevalim** [comment]
You must `require Explorer.DataFrame` in a previous cell before. There is an open issue to improve the error message for this in Elixir. :) Thank you!
