### ISSUE TITLE
Explorer NIF broken on FreeBSD

### ISSUE THREAD

**Issue by leonardorame** [elixir-explorer/explorer#907]
Hi, I've been trying to use Explorer on FreeBSD 14.0 and 13.1 (in a Jail on 14.0 host) and in both cases I get this:

My LiveBook has just this dependency:

```
Mix.install([
  {:explorer, "~> 0.8.2"}
])
```

```
15:09:05.779 [warning] The on_load function for module Elixir.Explorer.PolarsBackend.Native returned:
{:error,
 {:load_failed,
  ~c"Failed to load NIF library: '/usr/home/informemedico/.cache/mix/installs/elixir-1.16.2-erts-14.2.5/a7fbe39cd87ff258293b03c9b13e8458/_build/dev/lib/explorer/priv/native/libexplorer-v0.8.2-nif-2.15-x86_64-unknown-freebsd.so: No space available for static Thread Local Storage'"}}
```

Maybe the nif is compiled on a different O.S. version. Is there a way to let me compile it on my machine?

**Comment by philss** [comment]
Hey, @leonardorame 👋 

José added the instructions for manual compilation to the `README.md`, but just to complement: we are building for FreeBSD using the crosscompilation feature of the Rust compiler. I think it's not possible to target a specific version of that OS, so you need to compile in your machine.

Another tip is that you can specify the environment var in your `Mix.install/2` call:

```elixir
Mix.install([
  {:explorer, "~> 0.8.2"},
  {:rustler, ">= 0.0.0"} # Rustler is needed for the build.
], system_env: %{"EXPLORER_BUILD" => "1"})
```

Please check the README.md for more details about the dependencies (mostly the Rust toolchain).

**Comment by leonardorame** [comment]
Great @philss I'll try it later today.

**Comment by leonardorame** [comment]
Hi, I was able to compile it from the command line. rustc needed 11gb of Ram.

The build directory is `~/.cache/mix/installs/elixir-1.16.2-erts-14.2.5/b4bfc151806c51196f3b62c267bb60b4/_build/dev/lib/explorer/native/explorer/release/deps`, now, I would like to prevent a re-compilation. Should I leave this directory as is?

**Comment by philss** [comment]
@leonardorame yeah, you shouldn't remove the `_build` directory of your project. But if you are using `Mix.install/2`, be aware that changing any of the deps (or adding a new one) will trigger a recompilation. If you need something more stable, you can fork explorer, make a release, publish your artifact that was compiled, and point the RustlerPrecompiled config to your fork.

**Comment by leonardorame** [comment]
Let me see if I understood it.

The original Mix.install is:

```
Mix.install([
  {:explorer, "~> 0.8.2"},
  {:rustler, ">= 0.0.0"} # Rustler is needed for the build.
], system_env: %{"EXPLORER_BUILD" => "1"})
```

I must convert to this?:

```
Mix.install([
  {:explorer, "~> 0.8.2"},
  {:rustler, ">= 0.0.0"} # Rustler is needed for the build.
]
```

**Comment by philss** [comment]
@leonardorame no, the idea is to do something like I did in the [example project](https://github.com/philss/rustler_precompilation_example) with a fork of explorer, and them use that fork in your notebooks. It's kind of hard to maintain, but at least you won't have to recompile it every time.

Your installation would look like this:

```elixir
Mix.install([
  {:explorer, git: "yourgitrepo"}
])
```

But if you do not plan to change dependencies in your current project, I believe it's better to not go through all that work. I would suggest to maintain a fork just in case you need to use Explorer in production, or use in different notebooks.

**Comment by leonardorame** [comment]
Hi @philss I forked explorer, then did a `mix compile`, the dependency `adbc` didn't compile on FreeBSD so I commented it on `mix.exs`. Then it started to build, until I've got this error:

```
   ...  
   Compiling polars-time v0.38.3
   Compiling polars-io v0.38.3
   Compiling explorer v0.1.0 (/usr/home/informemedico/explorer/native/explorer)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 00s

11:13:20.530 [warning] The on_load function for module Elixir.Explorer.PolarsBackend.Native returned:
{:error,
 {:load_failed,
  ~c"Failed to load NIF library: '/usr/home/informemedico/explorer/_build/dev/lib/explorer/priv/native/libexplorer.so: No space available for static Thread Local Storage'"}}

Generated explorer app
```

Any hint?

**Comment by leonardorame** [comment]
I see `Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 00s`, how can I build a release (optimized without debug info)?

**Comment by josevalim** [comment]
Set `MIN_ENV=prod` env var perhaps?

**Comment by leonardorame** [comment]
Thanks @josevalim with `MIX_ENV=prod` I was able to build a `release`, but I still get the "No space available for static Thread Local Storage" error.

By reading this: https://lists.freebsd.org/archives/freebsd-hackers/2024-April/003182.html and exporting the LD_STATIC_TLS_EXTRA en var with a higher number than 128 it didn't fix the error. 

Now I'm looking at this: https://doc.rust-lang.org/beta/unstable-book/compiler-flags/tls-model.html but I don't know where can I set the `-Z tls-model` param for the build, could you point me to the right place?.

**Comment by leonardorame** [comment]
RUSTFLAGS="-Z tls-model=global-dynamic" mix compile -> Same error
RUSTFLAGS="-Z tls-model=local-dynamic" mix compile -> Same error
RUSTFLAGS="-Z tls-model=initial-exec" mix compile -> can't find crate for `tracing_attributes`
RUSTFLAGS="-Z tls-model=local-exec" mix compile -> many errors
RUSTFLAGS="-Z tls-model=emulated" mix compile -> many errors

It looks like there's no way to build explorer on FreeBSD.
