### ISSUE TITLE
[Not Issue] - Are the plans to use duckdb as an alternative backend?

### ISSUE THREAD

**Issue by kuatroka** [elixir-explorer/explorer#939]
Are the plans to use duckdb as an alternative backend?

I'm using both polars and duckdb in Python and find myself constantly preferring duckdb where possible. Less errors, less data types issues when reading multiple files, faster, deals the out of memory case with grace.

Thanks

**Comment by josevalim** [comment]
You can use DuckDB via ADBC: https://github.com/elixir-explorer/adbc

[Livebook](https://livebook.dev/) also has some smart cells to get you started.

**Comment by kuatroka** [comment]
Thanks, I'll check it out. 1st days in the Elixir land
