### ISSUE TITLE
Config to make table view default like in Polars itself

### ISSUE THREAD

**Issue by kuatroka** [elixir-explorer/explorer#948]
Hi, is there a setting/Config to make the Polars DataFrame view (like a table) to be a default view in Explorer instead of the sideways one? See the pic. Thanks.

![image](https://github.com/user-attachments/assets/8051f35e-8b22-47e1-b78f-e371af41c152)

**Comment by philss** [comment]
You can use [`kino_explorer`](https://github.com/livebook-dev/kino_explorer) that will give you a rich table automatically when you are on LiveBook.
