### ISSUE TITLE
Duckdb select statement only works on non first line in the cell

### ISSUE THREAD

**Issue by kuatroka** [elixir-explorer/explorer#949]
There seems to be a bug when running the SQL in a smart cell connected to duckdb. The SQL breaks if executed on the very first line of the cell. All other cell work fine. See the gif
![duckdb_livebook](https://github.com/user-attachments/assets/055b07ba-b466-4d0e-ac26-b9e76291068e)

**Comment by josevalim** [comment]
Can you please click on `<>` and show us the generated code for both cases?

**Comment by josevalim** [comment]
Also, does it work if you use `{{file}}` instead?

**Comment by kuatroka** [comment]
> Can you please click on `<>` and show us the generated code for both cases?

**When I type on the line 1, the code is:**
```
result =
  Explorer.DataFrame.from_query!(conn, "select * from read_parquet('\#{file}')", [])
 ```
 
**When I type on the line 2, the code is:**
```
result =
  Explorer.DataFrame.from_query!(
    conn,
    """

    select * from read_parquet('#{file}')
    """,
    []
  )
  ```
  
  > Also, does it work if you use {{file}} instead?

With this syntax everything works on both lines. I didn't know about this syntax. I was following Elixir syntax for referencing variables in text I found somewhere online

**Comment by josevalim** [comment]
Closing on https://github.com/livebook-dev/kino_db/pull/74.
