### ISSUE TITLE
Explorer.DataFrame.from_query/4 with :snowflake adapter returns dtype error on any numeric field

### ISSUE THREAD

**Issue by adworse** [elixir-explorer/explorer#952]
Error is "Generic Error: cannot cast to dtype: decimal[38,0]"

```elixir
{:error, "Generic Error: cannot cast to dtype: decimal[38,0]"}
    (explorer 0.8.3) lib/explorer/polars_backend/shared.ex:111: Explorer.PolarsBackend.Shared.df_dtypes/1
    (explorer 0.8.3) lib/explorer/polars_backend/shared.ex:97: Explorer.PolarsBackend.Shared.create_dataframe/1
    (explorer 0.8.3) lib/explorer/polars_backend/data_frame.ex:35: Explorer.PolarsBackend.DataFrame.from_query/3
    (explorer 0.8.3) lib/explorer/data_frame.ex:498: Explorer.DataFrame.from_query!/4
```

Error is reproducible in LiveBook with a trial SnowFlake AWS account. Unfortunately, my Rust knowledge is rather nonexistent.
I would be happy to share my trial creds with whoever feels generous enough to dive into fixing this one!

<img width="928" alt="Screenshot 2024-07-31 at 15 51 46" src="https://github.com/user-attachments/assets/2a0a93cb-7690-4d19-90f3-05d54d778767">

**Comment by josevalim** [comment]
We don't support decimals yet: #867. We will try to prioritize it sooner than later. :) Closing in favor of the other issue.

**Comment by adworse** [comment]
@josevalim Thank you for pointing this out! It seems like Snowflake reports its columns as decimal. Is there a chance one could force the type to float or int64 (since decimal[38,0] is, in fact, an integer)?

**Comment by josevalim** [comment]
You could try converting them to strings in your queries (explicitly select them as a string) and then cast them back to integers. The change you propose in itself would need to be requested to Snowflake's ADBC driver: https://github.com/apache/arrow-adbc
