### ISSUE TITLE
Discrepancy between typespec for Series.cast/2 (parameter dtype) and implementation

### ISSUE THREAD

**Issue by sesamzoo** [elixir-explorer/explorer#958]
At least in/until version 0.9.0, the [typespec of Series.cast/2](https://github.com/elixir-explorer/explorer/blob/v0.9.0/lib/explorer/series.ex#L1050) allows the type `dtype()` for its `dtype` parameter.

The `dtype()` spec doesn't include `:integer`.

`:integer` is used in one of the examples in the documentation and actually works.

I haven't checked for any other cases.

**Comment by philss** [comment]
Yeah, you are rignt.
I think we should accept `dtype() | dtype_alias()` - the last one could be `integer_dtype_alias() | float_dtype_alias()`. WDYT?

PRs are welcome :)
