### ISSUE TITLE
Mathematical operations are newline dependent in `summarise` macro

### ISSUE THREAD

**Issue by brendon9x** [elixir-explorer/explorer#964]
I'm sorry I haven't got the time to suggest a fix, but here's the problem shown by example:

<img width="915" alt="Screenshot 2024-08-17 at 16 38 42" src="https://github.com/user-attachments/assets/b57937a9-edcc-4b05-a1b5-5a27f33345a3">

I know there a few gotchas with macros, but I am assuming this is bug.

**Comment by josevalim** [comment]
This is expected, the same way as

```
a
+ b
```

in Elixir will return only `+b`. This happens because in Elixir, `(...)` is used to group both expressions and blocks.

**Comment by brendon9x** [comment]
Apologies – I did a search on Google, but I should have just tried in regular IEx.
