### ISSUE TITLE
how to set infer_schema=false for IO

### ISSUE THREAD

**Issue by lei0zhou** [elixir-explorer/explorer#970]
is it possible to have a argument that specify infer_schema as false, so that every value loaded as string for csv, ndjson, etc?

[infer_schema in polars::frame::row - Rust](https://docs.pola.rs/api/rust/dev/polars/frame/row/fn.infer_schema.html)

**Comment by josevalim** [comment]
You can set infer_schema_length: 0 :)

**Comment by josevalim** [comment]
Closing, I pushed a commit to improve the docs here.
